version: "3.8"
services:
  backend:
    build: ./backend 
    image: eu.gcr.io/quality-engineering-382310/qa-bank-backend-image:latest
    container_name: qa-bank-backend-container
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    image: eu.gcr.io/quality-engineering-382310/qa-bank-frontendend-image:latest
    container_name: qa-bank-frontend-container
    ports:
      - "3000:3000"
