version: "3.8"
services:
  backend:
    build: ./backend 
    image: qa-bank-backend-image
    container_name: qa-bank-backend-container
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    image: qa-bank-frontendend-image
    container_name: qa-bank-frontend-container
    ports:
      - "3000:3000"
